// Real 3D model library. Reads /models/models.json (generated by tools/scan-models.mjs) and loads GLBs placed in
// client/public/models/{weapons,characters,props}. Everything is optional: without a file the procedural model is used.
//
// Conventions (see docs/MODELS.md):
//   weapons/<id>.glb     metres, muzzle toward -Z, origin at the pistol grip; optional nodes: mag, bolt, slide, pump,
//                        cylinder, muzzle, eject, hand_right, hand_left (empties: palm position + rotation)
//   characters/t.glb, characters/ct.glb   rigged humanoid (Mixamo-style), facing +Z, clips named idle / walk / run /
//                        crouch / crouch_walk / jump / death (any casing, partial match); optional node weapon_socket
//   props/<key>.glb      crate, crate_stack, barrels, car, well, palm, container, pillar — origin on the floor, length on +X
export const models = {
  manifest: { weapons: {}, characters: {}, props: {} }, cache: new Map(), loader: null,
  async init(loader) {
    this.loader = loader;
    try { const r = await fetch('/models/models.json'); if (r.ok) this.manifest = { weapons: {}, characters: {}, props: {}, ...(await r.json()) }; } catch { /* no models */ }
    return this;
  },
  count() { return Object.keys(this.manifest.weapons).length + Object.keys(this.manifest.characters).length + Object.keys(this.manifest.props).length; },
  load(path) {
    if (!this.cache.has(path)) {
      const entry = { gltf: null, promise: null };
      entry.promise = this.loader.loadAsync(`/models/${path}`).then(g => { entry.gltf = g; g.scene.traverse(o => { if (o.isMesh) { o.castShadow = true; o.receiveShadow = true; o.geometry.userData.shared = true; for (const m of [].concat(o.material)) m.userData.shared = true; } }); return g; })
        .catch(error => { console.warn(`model ${path}:`, error.message); return null; });
      this.cache.set(path, entry);
    }
    return this.cache.get(path).promise;
  },
  /** Loads every weapon and character model up front so rigs can be built synchronously. */
  async preload(progress = () => {}) {
    const paths = [...Object.values(this.manifest.weapons), ...Object.values(this.manifest.characters)];
    let done = 0;
    await Promise.all(paths.map(p => this.load(p).then(() => progress(++done / paths.length))));
  },
  ready(path) { return path ? this.cache.get(path)?.gltf || null : null; },
  weapon(id) { return this.ready(this.manifest.weapons[id]); },
  character(team) { return this.ready(this.manifest.characters[team]); },
  propPath(key) { return this.manifest.props[key] || null; },
};
