services:
  - type: web
    name: kontir
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: "*"
      - key: MONGODB_URI
        sync: false
